name: Integração Contínua com Minunit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Instalar dependências
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compilar o projeto
      run: |
        gcc -o test/runtests test/runtests.c src/algoritmo.c -I src/ -I test/ -I test/miniunit-master -D TESTING

    - name: Executar testes
      run: |
        cd test && ./runtests 